### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by liquidbear99** [TadPath/PUMA#12] opened 2022-01-06 16:49 UTC
The FreeCAD folder does not contain all of the files. Ex. For making the stage you need the base plate, focus plate, etc but only the focus plate is in the FreeCAD folder.

**Comment by TadPath** [comment] 2022-01-06 17:59
Hello. Thanks for raising the issue. I have just downloaded the Stage.FCStd file from the repo to check. I can confirm that all the parts are there. It is just that not all of them are marked as 'visible'. You should see on the left hand panel the 'Base_plate' and 'Articulation' models are shaded out to indicate they are not currently visible. Just left click (once) on the model you want to see (to select it) and press space bar to toggle visibility on/off. I do not set all parts to visible in the files because this can overwhelm graphics card and slow up rendering. I will close the issue as there are no missing files / models I can see but do open another issue if you think a model is actually missing (as opposed to not currently visible). Please note that some models may also appear a bit odd depending on your graphics card settings (e.g. missing a wall) but the STL mesh you generate should be complete and printable (even if the printer complains of a mesh error) - you can check before you print using your slicer nozzle emulator to see if there are any real issues prior to printing. Thanks.

**Closed by TadPath** 2022-01-06 17:59 UTC

**Comment by liquidbear99** [comment] 2022-01-06 18:35
Thanks! That fixed it! I'm new to FreeCAD, sorry for taking your time away.
